Install script
f3flight/noip pull request #2
Opened 2017-08-20 22:41 UTC by bit-man

Hi,

Created an install script. Hope you like it and approve the pull request.

Thanks!

2017-10-13 19:28 UTC, bit-man commented
@f3flight could you take a look at this?
Thanks!

2017-10-13 19:34 UTC, f3flight commented
@bit-man sure, will check! I also will roll out an update soon which will allow automatic hostname confirm! so we will be able to ignore these "Confirm Your Hostname Now" emails - service will do that

2017-10-13 19:57 UTC, f3flight commented on install
> +    rm -rf ${folder[cfg]}
Please do not remove user configuration files on uninstall, unless they match default files exactly

2017-10-13 19:58 UTC, f3flight commented on install
> +  cp -R etc/noip/* ${folder[cfg]}
I've just lost my noip.conf =) please do not rewrite existing config files here

2017-10-13 19:58 UTC, f3flight requested changes
I've added comments, please address

2017-10-16 00:42 UTC, f3flight commented
@bit-man check out the updated version. Also, please fix the installer =)

2017-10-16 21:48 UTC, bit-man commented
@f3flight Intaller fixed !!

2017-11-10 19:44 UTC, merged